from coloradomesh.meshtastic.services.mqtt._base import (
    MQTTBroker,
    MeshtasticMQTTMessage,
    get_logger
)


class MeshtasticMQTTBroker(MQTTBroker):
    def __init__(self,
                 client_name: str,
                 root: str = "msh/US/CO/2/e/",
                 channel: str = "LongFast",
                 key: str = "AQ==",
                 on_admin_message_callback: Optional[Callable[MeshtasticMQTTMessage]] = None,
                 on_atak_forwarder_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_atak_plugin_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_audio_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_detection_sensor_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_ip_tunnel_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_neighbor_info_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_node_info_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_people_count_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_position_callback: Callable[[MeshtasticMQTTMessage], None] = None,
                 on_private_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_range_test_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_remote_hardware_control_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_reply_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_routing_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_serial_communication_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_simulator_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_store_and_forward_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_telemetry_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_text_message_callback: Callable[[MeshtasticMQTTMessage], None] = None,
                 on_compressed_text_message_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_traceroute_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_waypoint_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 on_zone_position_system_callback: Optional[Callable[[MeshtasticMQTTMessage], None]] = None,
                 logger: Optional[logging.Logger] = None
                 ):
        logger = logger or get_logger(name=client_name)
        super().__init__(
            client_name=client_name,
            broker_name="Meshtastic",
            broker_host="mqtt.meshtastic.org",
            broker_port=1883,
            root=root,
            username="meshdev",
            password="large4cats",
            channel="LongFast",
            key=key,
            on_admin_message_callback=on_admin_message_callback,
            on_atak_forwarder_message_callback=on_atak_forwarder_message_callback,
            on_atak_plugin_message_callback=on_atak_plugin_message_callback,
            on_audio_message_callback=on_audio_message_callback,
            on_detection_sensor_callback=on_detection_sensor_callback,
            on_ip_tunnel_message_callback=on_ip_tunnel_message_callback,
            on_neighbor_info_callback=on_neighbor_info_callback,
            on_node_info_callback=on_node_info_callback,
            on_people_count_callback=on_people_count_callback,
            on_position_callback=on_position_callback,
            on_private_message_callback=on_private_message_callback,
            on_range_test_callback=on_range_test_callback,
            on_remote_hardware_control_callback=on_remote_hardware_control_callback,
            on_reply_callback=on_reply_callback,
            on_routing_callback=on_routing_callback,
            on_serial_communication_callback=on_serial_communication_callback,
            on_simulator_callback=on_simulator_callback,
            on_store_and_forward_message_callback=on_store_and_forward_message_callback,
            on_telemetry_callback=on_telemetry_callback,
            on_text_message_callback=on_text_message_callback,
            on_compressed_text_message_callback=on_compressed_text_message_callback,
            on_traceroute_callback=on_traceroute_callback,
            on_waypoint_callback=on_waypoint_callback,
            on_zone_position_system_callback=on_zone_position_system_callback,
            logger=logger
        )
